### ISSUE TITLE
Refresh buttons on clan? What do they do?

### ISSUE THREAD

**Issue by Osein** [Osein/bitefight#22]
I cant seem to find their exact function. Anyone can help me with that?

**Comment by khizhnik** [comment]
If you asked about /clan/memberlist/ then in original game it's just refresh the page.

**Comment by Osein** [comment]
I think every person has their own timer and when someone puts a donate after that time, it shows donated amount in green.

After refresh every green donate turns to normal, but I am not sure lol

**Comment by khizhnik** [comment]
I think you are right. This feature is likely to work on the server crontab and refresh output data every 5 minutes (maybe more or less I don't know for sure). And a button does the same thing only without reference to the crontab on the server.

**Comment by Osein** [comment]
Donation refresh is done but blood refresh will took time, so to the todo list lol
