### ISSUE TITLE
Need your advice

### ISSUE THREAD

**Issue by khizhnik** [Osein/bitefight#23]
Hello!
I saw your post on ragezone and interested at Falcone. I put the server, set php7 and Falcon. In config.php set the baseurl to public folder. After that I wanted to look the links structure and how to write code in falcone but I stuck. Links on site don't work, page reloaded, url has changed but page still the same. Any ideas how to fix it?

**Comment by Osein** [comment]
1. I pointed my domain to public folder in apache configs. Try that
2. Make sure that you opened overriding htaccess in apache
3. Try to comment out this line https://github.com/Osein/bitefight/blob/master/routes.php#L10

**Comment by khizhnik** [comment]
Thank you for a quick reply!!! Problem was solved.

Found some bugs. If you need help with testing just say. 
I took your code for study purposes as phalcone example code))) Hope it will help me to understand this framework well.

**Comment by Osein** [comment]
Maybe you can share how you solved it for others?

Phalcon is a big framework, so i suggest you to go find some pdfs or read documentation to create your own style. Bitefight is not that big, so I skipped module system, access control layer and phalcons own database layer. Be sure to check them out

**Comment by khizhnik** [comment]
I did as you said. At first I pointed my domain to public folder in apache configs. And it solved the problem.
But later I wondered what if? And try another method. 
I change back Apache config and comment line 10 in routes.php  and it worked too.

For now I leave this hack witch comment line.
