### ISSUE TITLE
Some bugs I've found

### ISSUE THREAD

**Issue by khizhnik** [Osein/bitefight#24]
1. /public/highscore - on click player name page give result  -- string(1) "2"
2. /public/city/index - image 0.gif has url /image/city/0.gif instead of /public/image/city/0.gif
3. /public/city/graveyard - after pressing button Go! return SQLSTATE[42S22]: Column not found: 1054 Unknown column 'start_time' in 'field list' 
4. /public/hideout - after upgrade Domicile to level 8 money not charged (Need to re-check bug I'm not sure in it)
5. Not bug I think but might you didn't know it. If you change url to http://url/views/ you will see page php functions for index.phtml. Same way you can look the code for other directories.

**Comment by Osein** [comment]
1. Highscore page is still in development so there is some unfinished parts probably I forgot some var_dumps there...
2. This is probably because your cdn config, if you didn't point public folder in apache you have to include public in config like http://xxx.xx/public/
3. I will update database to latest sql right now
4. Fixed
5. Again, public problem lol just point public in your apache configs 😆 All folders need some empty fake index.htmls

**Comment by khizhnik** [comment]
2.  CDN setting correct. 
Ok. I think use hack isn't a good idea)) Will change apache setting soon.

**Comment by Osein** [comment]
I added an htaccess file to root folder, and pointed root folder in apache, problems seem fixed

**Comment by khizhnik** [comment]
Ok. I've made apache settings correct. Problems fixed. Also downloaded new files from your git to compare with older version for my education. 

6. On clan page     Members	1 / 1 Member - link path to  http://s202.en.bitefight.gameforge.com/clan/memberlist/9267 
7. On clan page Logo - link path http://s202.en.bitefight.gameforge.com/clan/logo

P.S: Also I found one more tester for your game script. Hope we will help you in your work.
P.S.S: As for me I'm in love with Phalcon framework. It makes code much more easier. Before I'm using only php + mysql + some javascript to coding. Still looking for a good literature on my native language to study phalcone :(

**Comment by Osein** [comment]
If there is no page prepared for a link I leave them lol I think shop is more important from clan, items ❤️

**Comment by khizhnik** [comment]
Оk. Didn't know that. For this kind of links I'm using # instead of link. 

8. It's not bug but))) If I want to write some Notepad notes or "RPG-description of your character" in mobile browser (chrome mobile) text area increased and hides button "save". 

9. In Hideout Landscape level 6 costs 32.768. Character has 37.939 gold but link to upgarde not active.
10. Action points 1 / 125 at the end of hunting.  0 / 125 in original game.
