### ISSUE TITLE
No page works out of homepage

### ISSUE THREAD

**Issue by krehak** [Osein/bitefight#35]
So I installed Phalcon, created database, edited config. But when I enter the page (on localhost) homepage loads just fine, but when I click on any link (news, login, register...) nothing works and I'm still on the homepage. Like it doesn't recognize other pages. I haven't installed it right on the localhost, but localhost/bitefight so I also changed CDN_URL and BASE_URL = 'http://localhost/bitefight/'; in config.php. Did I miss something?

**Comment by Osein** [comment]
Probably apache configuration error, I havent tested it with installing it under a folder. 

Try commenting out this line, https://github.com/Osein/bitefight/blob/master/routes.php#L10

Or open a virtual host on apache or nginx and redirect a local domain to public folder

Or you have to wait for me to go home lol

**Comment by krehak** [comment]
Thanks, that helped! Also I found out it to working with command "php -S localhost:8000 -t public" and then it works right under "localhost:8000" (and changing it in the config.php of course). But in both ways I get this error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bitefight.message' doesn't exist

I have imported a "development.sql" to my mysql database and it seems to be missing table "message".

By the way, I have some more question if I can :)
- I found file /lang/en.php - does it mean that it can support multi-languages?
- is it possible to change the server speed? (default sets to 4 as said in homepage)
- are you going to implement an administration, so we can add custom items and their images?

**Comment by Osein** [comment]
First of all I have to update database, sorry for that. Sql is old. I forgot that 😞 

A lot of page strings in language file, but not all of them. That means we will support translate in future or before release. ( Every string in that file is in views. )
Server speed variable is going to 'todo' list.
Administration is in last position on my todo list

**Comment by krehak** [comment]
Ok, I will do my language translation in meanwhile then I can send it to you, so you can test it later.
I consider this as closed issue and will wait for SQL update. Thanks.

**Comment by Osein** [comment]
In 4 - 6 hour I will update database sql, and you can send pull request or send file directly to me if you do progress on your translation

**Comment by krehak** [comment]
I'm more like bitbucket (mercurial) man, so I don't have git client also don't know how it works :) How can I send it to you directly?

**Comment by Osein** [comment]
Maybe create a gist file and add here its link as a comment

**Comment by Osein** [comment]
New sql is here, sorry for the delay

**Comment by krehak** [comment]
No problem, i haven't been at home anyway :)

BTW thanks for SQL update.

**Comment by krehak** [comment]
I just extended hideout domicile, since level 12, 13 and 14 were missing files, there was "no house". So I add customizations for those levels. Put them into **/public/img/hidout/1/u/**

[u.zip](https://github.com/Osein/bitefight/files/998502/u.zip)

**Comment by Osein** [comment]
Oh I didnt see them, added, thank you
