### ISSUE TITLE
still alive ?

### ISSUE THREAD

**Issue by Goten87** [Osein/bitefight#38]
so is this still alive ? or death already

**Comment by Osein** [comment]
Still alive but i dont see anyone using it so i am kinda getting lazy

**Comment by oguzzarci** [comment]
Hüseyin merhaba, geçenlerde denemiştim bir hata veriyordu. Ama herşeyi çok
güzel olmuş eline sağlık.

6 Oca 2018 ÖS 9:17 tarihinde "Hasan Hüseyin Gücüyener" <
notifications@github.com> yazdı:

**Comment by Osein** [comment]
Millet phalcon yükleyemiyor o yüzden laravele geçmeyi planlıyorum aslında

**Comment by Goten87** [comment]
Well I don’t have others to use it but I can install it in my dev pc to test stuff on my own I think

**Comment by Goten87** [comment]
Also don’t know what u where talking about but google translate the things u sayed returns a fun replay something about a rabbit :p for osein

**Comment by Osein** [comment]
Lololol i was telling that i am planning to switch to laravel. People cant install phalcon it is kinda advanced one to figure out for newbies

**Comment by Goten87** [comment]
well then i will wait with installing it go for it switch to laravel then i will try to install it on my home server
and test it

**Comment by Goten87** [comment]
and i will join it i think to make it dutch or somthing xD
started making nl.php for u xD so u can include it later on hope not mutch will chance when u go over to laravel

**Comment by Osein** [comment]
better start slowly lol

**Comment by Goten87** [comment]
I have a little knowledge about php so I’ll be fine also something like a discord server we can talk on sons I think where in the same time zone I’m in eu

**Comment by Osein** [comment]
Closing this issue because laravel development is started. For questions feel free to join discord channel
