### ISSUE TITLE
Recreate database with migrations

### ISSUE THREAD

**Issue by mattdeveluk** [Osein/bitefight#39]
Hello, where can I find .sql file for this project ? I tried creating db with artisan db:seed, but nothing happened. Can you help ?

**Comment by Goten87** [comment]
It’s as far as I know artisan migrate:install

**Comment by Osein** [comment]
Well fuck. I didnt put sql file after I got switched to laravel.. Have to recreate what I created in laravel again. I dont have that database cuz I got my computer stolen

Last committed sql is here:
https://github.com/Osein/bitefight/blob/6478ce8983232fca5d17970f2166b58809913fc6/development.sql

**Comment by Osein** [comment]
Oh man I forgot I did that lol.

Just run "php artisan migrate" 😅
