### ISSUE TITLE
Important Question for me

### ISSUE THREAD

**Issue by MehmetDT** [Osein/bitefight#44]
Hello firstly thanks for this repo. I have a question , ı want to make a mobile game with this repo assets/images .. Can ı make ? Is this legal ? Is it a problem ?  I don't know how it works copyright .

**Comment by silqir** [comment]
This is legal because it uses the Laravel framework (open source) but inside it contains copyrights such as images, brands, etc. The original game itself is bitefight, you can make it legal if you change the image, name and associated with the game bitefight.

**Comment by Osein** [comment]
Code does not have any license, you can use it freely but you can't use assets or copyrighted names.
